name = "UHTP"
uuid = "12345678-1234-1234-1234-123456789abc"
authors = ["AI-DLC Team"]
version = "0.1.0"

[deps]
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
Sockets = "6462fe0b-24de-5631-8697-dd941f90decc"
StaticArrays = "90137ffa-7385-5640-81b9-e52037218182"
YAML = "ddb6d928-2868-570f-bddf-ab3f9cf99eb6"

[compat]
julia = "1.10"
StaticArrays = "1.9"
YAML = "0.4"
